sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)

script:
  - docker image build -t azsuth/beefy-gainz-router:latest -t azsuth/beefy-gainz-router:$SHA .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push azsuth/beefy-gainz-router:latest
  - docker push azsuth/beefy-gainz-router:$SHA